=== Anouar-Chouirdi/Lenguaje-de-Marcas/practica_XML_Anuar/practica3_xml/ejercicio1/cuentos.dtd
<!ELEMENT cuento (personajes, trama, etiqueta*, precio?)>
<!ATTLIST cuento 
    cod CDATA #REQUIRED
    titulo CDATA #REQUIRED
>

<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre, genero)>
<!ATTLIST personaje 
    id ID #REQUIRED
    tipo (principal | secundario | antagonista) "principal"
>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta 
    nombre CDATA #REQUIRED
>

<!ELEMENT precio (#PCDATA)>

=== Anouar-Chouirdi/Lenguaje-de-Marcas/practica_XML_Anuar/practica3_xml/ejercicio1/cuento1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: [Anoaur Chouirdi Alouat] 
Curso: [Asir1] 
Fecha: [2/04/2025] 
Ejercicio: [Cuento] 
-->
<!DOCTYPE cuento SYSTEM "cuentos.dtd">
<cuento cod="A01" titulo="El Bosque Encantado">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Alicia</nombre>
            <genero>F</genero>
        </personaje>
    </personajes>
    <trama>Una joven aventurera explora un bosque m√°gico.</trama>
    <etiqueta nombre="aventura"/>
    <precio>5.99</precio>
</cuento>

=== Anouar-Chouirdi/Lenguaje-de-Marcas/practica_XML_Anuar/practica3_xml/ejercicio1/cuento2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: [Anoaur Chouirdi Alouat] 
Curso: [Asir1] 
Fecha: [2/04/2025] 
Ejercicio: [Cuento] 
-->
<!DOCTYPE cuento SYSTEM "cuentos.dtd">
<cuento cod="B02" titulo="La Casa del Terror">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Pedro</nombre>
            <genero>M</genero>
        </personaje>
    </personajes>
    <trama>Anouar explora una casa embrujada y descubre secretos oscuros.</trama>
    <etiqueta nombre="terror"/>
    <precio>3.50</precio>
</cuento>
